/**
 * Getting out.
 *
 * Arrival is the half everybody demonstrates and the easy one: it spreads over
 * three hours and every person in it chooses when to make it. Egress is
 * seventy-six thousand people deciding at the same whistle, onto a network that
 * is already carrying the city's ordinary Sunday. It is the harder problem, it
 * is the one venue operations actually loses sleep over, and it is invisible in
 * a model that stops at the property line.
 *
 * What this draws is not a simulation and does not pretend to be. It is CDOT's
 * own published counts on the roads the lots feed onto, coloured by how much
 * room those roads have left - and the answer, which is the whole point, is
 * almost none. Every arterial ringing this stadium runs at or over nine tenths
 * of capacity at the design hour on an average day. I-25 is over 1.0 before a
 * single car leaves the north lot.
 *
 * The arithmetic beside it is deliberately the kind you can check in your head:
 * a sellout, an occupancy figure that is stated rather than hidden, and the
 * vehicle count that falls out of the two. No curve fitting, no claimed model.
 * Somebody who disagrees with the occupancy figure can see exactly which number
 * to argue with, which is the difference between an estimate and an assertion.
 *
 * ## Why the counts are baked in
 *
 * data/traffic.json is generated by tools/build_traffic.py and committed. The
 * source is a state DOT's own server, the figures change once a year, and the
 * app is a demo that has to work in a conference room on somebody else's wifi.
 * Fetching it live would trade all of that for a freshness nobody would notice.
 */
/**
 * Fetched when the panel is first opened, not when the file is parsed.
 *
 * The rest of the app is careful about this - the measurement widgets and the
 * time slider are both pulled in on demand - and a feature layer nobody has
 * asked for has no business on the critical path of a cold load. A viewer who
 * never presses E never fetches it.
 */
let FeatureLayer = null;
const kit = () => (FeatureLayer
  ? Promise.resolve(FeatureLayer)
  : import("https://js.arcgis.com/5.0/@arcgis/core/layers/FeatureLayer.js")
      .then((m) => (FeatureLayer = m.default)));

/**
 * How full is full.
 *
 * CDOT's VCRATIO is volume over capacity at the design hour, so 1.0 is not
 * "busy" - it is the point at which the road has run out. The breaks are set
 * around that rather than evenly: what matters is which side of full a road is
 * on, and how close the ones below it are.
 */
const BREAKS = [
  { max: 0.70, color: [122, 184, 132], label: "Room to spare" },
  { max: 0.90, color: [226, 189, 92], label: "Filling up" },
  { max: 1.00, color: [232, 130, 58], label: "At capacity" },
  { max: 99, color: [214, 69, 55], label: "Over capacity" }
];

const colorFor = (vc) => (BREAKS.find((b) => vc < b.max) ?? BREAKS[3]).color;

export function buildEgress(view, CONFIG) {
  let layer = null;
  let doc = null;
  let loading = null;

  async function load() {
    if (doc) return doc;
    if (!loading) {
      loading = fetch(CONFIG.egress.data, { cache: "force-cache" })
        .then((r) => {
          if (!r.ok) throw new Error(`traffic ${r.status}`);
          return r.json();
        })
        .then((d) => { doc = d; return d; });
    }
    return loading;
  }

  function makeLayer(d) {
    const graphics = d.segments.map((s, i) => ({
      geometry: {
        type: "polyline",
        paths: s.paths,
        spatialReference: { wkid: 4326 }
      },
      attributes: {
        ObjectID: i + 1,
        name: s.name,
        also: s.also ?? "",
        aadt: s.aadt,
        capacity: s.capacity,
        vc: s.vc
      }
    }));

    return new FeatureLayer({
      title: "Traffic",
      source: graphics,
      objectIdField: "ObjectID",
      geometryType: "polyline",
      spatialReference: { wkid: 4326 },
      fields: [
        { name: "ObjectID", type: "oid" },
        { name: "name", type: "string" },
        { name: "also", type: "string" },
        { name: "aadt", type: "integer" },
        { name: "capacity", type: "integer" },
        { name: "vc", type: "double" }
      ],
      // Lifted clear of the ground rather than draped on it. The captures sit
      // above the terrain surface - that is what an integrated mesh is - so a
      // line drawn on the terrain is a line drawn underneath the roads it is
      // describing, and it disappears the moment the camera is anywhere near
      // the venue.
      elevationInfo: { mode: "relative-to-ground", offset: 8 },
      renderer: {
        type: "class-breaks",
        field: "vc",
        classBreakInfos: BREAKS.map((b, i) => ({
          minValue: i === 0 ? -1 : BREAKS[i - 1].max,
          maxValue: b.max,
          label: b.label,
          symbol: {
            type: "line-3d",
            symbolLayers: [{
              type: "line",
              // Screen space, so the indicator stays readable from a seat and
              // from five hundred metres up. A real-world width would be a
              // ribbon at one end and invisible at the other.
              size: 4,
              material: { color: b.color },
              cap: "round",
              join: "round"
            }]
          }
        })),
        // Width carries the volume, colour carries how full. A fat red line is
        // a big road with nothing left, which is the thing worth seeing first.
        visualVariables: [{
          type: "size",
          field: "aadt",
          stops: [
            { value: 10000, size: 2.5 },
            { value: 60000, size: 5 },
            { value: 290000, size: 11 }
          ]
        }]
      },
      popupTemplate: {
        title: "{name}",
        content: [{
          type: "fields",
          fieldInfos: [
            { fieldName: "also", label: "Also known as" },
            { fieldName: "aadt", label: "Vehicles a day (annual average)",
              format: { digitSeparator: true, places: 0 } },
            { fieldName: "capacity", label: "Capacity an hour",
              format: { digitSeparator: true, places: 0 } },
            { fieldName: "vc", label: "Volume over capacity, design hour",
              format: { places: 2 } }
          ]
        }]
      }
    });
  }

  /**
   * The arithmetic, worked out from the counts and the two stated assumptions.
   *
   * Returned rather than rendered so the panel owns the words. Every figure
   * here is either published or a division of two published figures, and the
   * occupancy is the one input that is neither - which is why it is handed back
   * alongside the answer rather than folded into it.
   */
  function sums(d) {
    const seats = CONFIG.egress.capacity;
    const per = CONFIG.egress.perVehicle;
    const cars = Math.round(seats / per);
    // One row per route rather than per segment: a road is a road, and the
    // worst stretch of it is the one that decides how long everybody sits.
    const routes = new Map();
    for (const s of d.segments) {
      const r = routes.get(s.name) ?? { name: s.name, also: s.also, aadt: 0, vc: 0 };
      r.aadt = Math.max(r.aadt, s.aadt);
      r.vc = Math.max(r.vc, s.vc);
      routes.set(s.name, r);
    }
    const ring = [...routes.values()].sort((a, b) => b.aadt - a.aadt);
    return {
      seats, per, cars, ring,
      full: ring.filter((r) => r.vc >= 1).length,
      tight: ring.filter((r) => r.vc >= 0.9).length,
      year: d.year,
      source: d.source
    };
  }

  return {
    /** The counts and the arithmetic, loaded once. */
    async data() {
      const d = await load();
      return { doc: d, sums: sums(d) };
    },
    async show(on) {
      if (!on) { if (layer) layer.visible = false; return; }
      const [d] = await Promise.all([load(), kit()]);
      if (!layer) {
        layer = makeLayer(d);
        view.map.add(layer);
      }
      layer.visible = true;
    },
    get shown() { return !!layer && layer.visible; },
    /** The legend, so the panel and the map cannot disagree about a colour. */
    breaks: BREAKS
  };
}
